FILE="./.env"

cat <<EOM >> $FILE
    DEBUG=${DEBUG:-false}
    NEXT_TELEMETRY_DISABLED=1
EOM

if [[ $TRAVIS_BRANCH == 'dev' ]]; then
cat <<EOM >> $FILE
    NEXT_PUBLIC_APP_ENV=dev
    NEXT_PUBLIC_BASE_PATH=/app
    NEXT_PUBLIC_DEFAULT_CATALOG_ID=mDohaxCG
    NEXT_PUBLIC_SEGMENT_API_KEY=${NEXT_PUBLIC_SEGMENT_DEV_API_KEY:-7ec0ad3387fFFFFNRAL}
    NEXT_PUBLIC_REVAL_SECRET_TOKEN=${NEXT_PUBLIC_REVAL_DEV_SECRET_TOKEN:-test123}
    NEXT_PUBLIC_DOCUMENTHUB_LIBRARY_ID=4l3Kesw
EOM
    echo "=========== $TRAVIS_BRANCH ENV ==========="
    cat $FILE
elif [[ $TRAVIS_BRANCH == 'main' ]]; then
cat <<EOM >> $FILE
    NEXT_PUBLIC_APP_ENV=live
    NEXT_PUBLIC_BASE_PATH=/app
    NEXT_PUBLIC_DEFAULT_CATALOG_ID=mDohaxCG
    NEXT_PUBLIC_SEGMENT_API_KEY=${NEXT_PUBLIC_SEGMENT_LIVE_API_KEY:-7ec0ad3387fFFFFNRAL}
    NEXT_PUBLIC_REVAL_SECRET_TOKEN=${NEXT_PUBLIC_REVAL_LIVE_SECRET_TOKEN:-test123}
    NEXT_PUBLIC_DOCUMENTHUB_LIBRARY_ID=4l3Kesw
EOM
    echo "=========== $TRAVIS_BRANCH ENV ==========="
    cat $FILE
else
    exit 0
fi
